spring.application.name=Roles_And_Permissions

spring.datasource.url=jdbc:mysql://localhost:3306/roles_permission_db
spring.datasource.username=root
spring.datasource.password=Pass123@

server.servlet.context-path=/api/v1

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.defer-datasource-initialization=true

spring.sql.init.mode=never
spring.sql.init.data-locations=classpath:data.sql

# Secure Secret Key.
jwt.secretKey=hxhxiiudfjd4484b4gb5j9gfk448jrjfff94hfn4dttb5iw36v3nfu68hggudjjdilr48urltaftfhl9
